openapi: 3.0.3
info:
  title: STD23107 - TD5
  version: 1.0.5
servers:
  - url: https://localhost.STD23107-TD1.com
paths:
  /customers:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
        required: true
      responses:
        200:
          description: Customer updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerPatch"
        required: true
      responses:
        200:
          description: Customer partially updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
    CustomerPatch:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
